# Generated by Django 5.0.4 on 2024-04-15 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 22, 3, 15, 520746, tzinfo=datetime.timezone.utc)),
        ),
    ]
