# Generated by Django 5.0.4 on 2024-04-15 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 22, 5, 16, 615967, tzinfo=datetime.timezone.utc)),
        ),
    ]
