# Generated by Django 5.0.4 on 2024-04-21 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_total_price_alter_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 20, 34, 24, 863243, tzinfo=datetime.timezone.utc)),
        ),
    ]
