# Generated by Django 5.0.4 on 2024-04-21 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cartitem_item_price_alter_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 20, 37, 38, 154194, tzinfo=datetime.timezone.utc)),
        ),
    ]
