# Generated by Django 5.0.4 on 2024-04-21 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_item_liked_by_user_alter_item_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='liked_by_user',
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 21, 40, 28, 598882, tzinfo=datetime.timezone.utc)),
        ),
    ]
